const FETCH_ARTICLES_INIT = 'FETCH_ARTICLES_INIT';
const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';
const FETCH_UNIQUE_ARTICLE_INIT = 'FETCH_UNIQUE_ARTICLE_INIT';
const FETCH_UNIQUE_ARTICLE_SUCCESS = 'FETCH_UNIQUE_ARTICLE_SUCCESS';
const FETCH_UNIQUE_ARTICLE_FAILURE = 'FETCH_UNIQUE_ARTICLE_FAILURE';

export default {
  FETCH_ARTICLES_INIT,
  FETCH_ARTICLES_SUCCESS,
  FETCH_ARTICLES_FAILURE,
  FETCH_UNIQUE_ARTICLE_INIT,
  FETCH_UNIQUE_ARTICLE_SUCCESS,
  FETCH_UNIQUE_ARTICLE_FAILURE,
};
